eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-suply
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource

# 配置mybatis